FROM abernix/meteord:base
LABEL maintainer "jfrancois@clapnclip.com"

# @see from https://github.com/nachochip/ffmpeg/blob/master/Dockerfile
ADD 	ffmpeg.tar.gz	/usr/local/
ADD 	libc.conf 	/etc/ld.so.conf.d/
